#!/usr/bin/env python3
"""migrate_manual_bindings.py - bring the hand-written std/*.d.pengu bindings in line.

Those files are maintained by hand, so they are *merged* rather than
regenerated: the C header (through ``pengu bind``) is the source of truth for
**signatures** — which is where `const` → `frozen` lives — while everything the
file adds (preamble, section banners, extra aliases, hand-picked ``insignia`` and
``link`` lines, deliberately dropped symbols) is preserved.

Per file it:

* converts ``## …`` comments to single-line ``# …`` (the generated banner keeps
  ``##``), matching what the generator emits;
* replaces the signature of a ``declare``/``alias`` with the generated one when
  the parameter *names* line up, so every ``const`` qualifier becomes ``frozen``
  and a stale type is corrected;
* adds the ``import`` lines the generated binding declares for headers it
  includes (``rlights.h`` includes ``raylib.h``), if they are missing;
* keeps and reports anything else.

Usage::

    python migrate_manual_bindings.py --check     # report only (default)
    python migrate_manual_bindings.py --write     # apply
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pengu_bind import generate_bind_file  # noqa: E402

STD = Path("std")
REPO = Path(__file__).resolve().parent
SEARCH_DIRS = ["std_c", "build/include", "extern"]
BANNER_KEEP = re.compile(r"^##\s*(PenguScript declaration binding generated|Source header:)")
DECL_RE = re.compile(r"^(declare\s+([A-Za-z_]\w*)|alias\s+([A-Za-z_]\w*)\s+as)\b(.*)$")
INCLUDE_RE = re.compile(r'^\s*include\s+"([^"]+)"')

# Bindings that were written (or heavily curated) by hand and carry no
# "generated by 'pengu bind'" banner.
MANUAL_BINDINGS = [
    "miniaudio.d.pengu", "minicoro.d.pengu", "raylib.d.pengu", "rlights.d.pengu",
    "sqlite3.d.pengu", "tomlum.d.pengu", "uuid.d.pengu", "webui.d.pengu",
    "xlsxio.d.pengu", "xxhash.d.pengu", "yaml.d.pengu",
]


def find_header(name: str) -> Optional[str]:
    """Locates a C header by name in the repository's include trees."""
    for base in SEARCH_DIRS:
        direct = REPO / base / name
        if direct.is_file():
            return str(direct)
    for base in SEARCH_DIRS:
        for dirpath, _dirs, files in os.walk(REPO / base):
            if name in files:
                return os.path.join(dirpath, name)
    return None


def split_top_level(text: str) -> List[str]:
    """Splits on commas outside parentheses/brackets (callback types contain commas)."""
    out: List[str] = []
    depth, current = 0, ""
    for ch in text:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(current)
            current = ""
            continue
        current += ch
    out.append(current)
    return out


def signature(line: str) -> Tuple[List[str], str]:
    """Returns (parameter names, parameter text) of a declare/alias line."""
    body = re.sub(r"^(declare|alias)\s+\S+", "", line).strip()
    body = re.sub(r"^as\s+ref\s+to\s+weave", "", body).strip()
    if " into " in body:
        body = body.rsplit(" into ", 1)[0].strip()
    body = re.sub(r"^with\s+", "", body).strip()
    parts = [p.strip() for p in split_top_level(body) if p.strip()]
    return [p.split(" as ", 1)[0].strip() for p in parts], body


def generate(header_path: str) -> str:
    """Runs the generator for one header and returns the produced text."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, Path(header_path).stem + ".d.pengu")
        generate_bind_file(
            header_path,
            output=out,
            include_paths=[str(REPO / "std_c"), str(REPO / "build/include"),
                           os.path.dirname(header_path), str(REPO)],
            auto_import=str(STD),
        )
        return Path(out).read_text(encoding="utf-8")


def generated_declarations(fresh_text: str) -> Dict[str, str]:
    """Maps declaration name -> generated signature line."""
    found: Dict[str, str] = {}
    for line in fresh_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = DECL_RE.match(stripped)
        if m:
            found[m.group(2) or m.group(3)] = stripped
    return found


def migrate(path: Path, write: bool) -> Tuple[str, List[str]]:
    """Migrates one binding. Returns (status, notes)."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    header = next((m.group(1) for m in (INCLUDE_RE.match(l) for l in lines) if m), None)
    if not header:
        return "skipped", ["no include line"]
    header_path = find_header(header)
    if not header_path:
        return "skipped", [f"header '{header}' not found"]

    try:
        fresh_text = generate(header_path)
    except Exception as exc:  # noqa: BLE001 - some vendored headers need libs we lack
        return "skipped", [f"cannot preprocess ({type(exc).__name__}): "
                           f"{str(exc).splitlines()[0][:70]}"]
    fresh = generated_declarations(fresh_text)

    out: List[str] = []
    replaced = 0
    kept = 0
    notes: List[str] = []
    for line in lines:
        stripped = line.strip()
        indent = line[: len(line) - len(line.lstrip())]

        if stripped.startswith("##") and not BANNER_KEEP.match(stripped):
            out.append(f"{indent}#{stripped[2:]}")
            continue

        m = DECL_RE.match(stripped)
        if m:
            name = m.group(2) or m.group(3)
            fresh_line = fresh.get(name)
            if fresh_line and fresh_line != stripped:
                old_names, _ = signature(stripped)
                new_names, _ = signature(fresh_line)
                if old_names == new_names:
                    out.append(f"{indent}{fresh_line}")
                    replaced += 1
                    continue
                kept += 1
                notes.append(f"{name}: signature kept (params differ)")
            out.append(line)
            continue

        out.append(line)

    added_imports: List[str] = []
    for line in fresh_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("import ") and stripped not in text:
            added_imports.append(stripped)
    if added_imports:
        for i, line in enumerate(out):
            if INCLUDE_RE.match(line):
                out[i + 1: i + 1] = [""] + added_imports
                break

    result = "\n".join(out)

    # Safety nets: the merge may only rewrite signatures, and the result must
    # still be valid PenguScript. Anything else is reported and skipped.
    decl_count = len(re.findall(r"^(declare|alias|rune|omen|echo|seal|const)\b", text, re.MULTILINE))
    new_count = len(re.findall(r"^(declare|alias|rune|omen|echo|seal|const)\b", result, re.MULTILINE))
    if new_count < decl_count:
        return "skipped", [f"declarations lost ({decl_count} -> {new_count}); not written"]
    from pengu_parser.pengu_parser import PenguParser

    try:
        PenguParser().parse(result)
    except Exception as exc:  # noqa: BLE001
        return "skipped", [f"result does not parse: {str(exc).splitlines()[0][:70]}"]

    detail = [f"{replaced} signature(s) refreshed"]
    if kept:
        detail.append(f"{kept} kept")
    if added_imports:
        detail.append("imports: " + ", ".join(added_imports))
    if result == text:
        detail.append("no change")
    elif write:
        path.write_text(result, encoding="utf-8")
    return ("written" if write else "would-write"), detail + notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Apply the changes")
    parser.add_argument("--check", action="store_true", help="Report only (default)")
    parser.add_argument("--only", default="", help="Migrate a single file name")
    args = parser.parse_args()

    for name in MANUAL_BINDINGS:
        if args.only and name != args.only:
            continue
        status, notes = migrate(STD / name, args.write)
        print(f"[{status:11}] {name:24} " + "; ".join(notes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
