#!/usr/bin/env python3
"""pengu_assets.py — Generates src/<module>.pengu and build/<module>_assets.c for project assets."""

from __future__ import annotations

import fnmatch
import hashlib
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple, Union

DEFAULT_MODULE = "arca"
DEFAULT_ASSETS_DIR = "assets"


def _sanitize_module(module: str) -> str:
    """Sanitizes module name to be a valid C and PenguScript identifier."""
    s = re.sub(r"[^A-Za-z0-9_]", "_", module)
    if not s or s[0].isdigit():
        s = "_" + s
    return s


@dataclass
class AssetConfig:
    project_root: Path
    src_dir: Path
    build_dir: Path
    assets_dir: Path
    module: str = DEFAULT_MODULE
    embed: bool = True
    exclude: List[str] = field(default_factory=list)

    def __post_init__(self):
        self.module = _sanitize_module(self.module or DEFAULT_MODULE)


def _c_escape(s: str) -> str:
    """Escapes backslashes and double quotes for C string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _c_ident(name: str) -> str:
    """Stable C identifier derived from the logical asset path, collision-free."""
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    h = hashlib.sha1(name.encode("utf-8")).hexdigest()[:8]
    return f"_asset_{cleaned}_{h}"


def _asset_const_name(name: str) -> str:
    """Uppercase PenguScript identifier for asset constants, e.g. ASSET_LOGO_PNG_A1B2C3D4."""
    cleaned = re.sub(r"[^A-Za-z0-9]", "_", name).upper()
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    h = hashlib.sha1(name.encode("utf-8")).hexdigest()[:8].upper()
    return f"ASSET_{cleaned}_{h}"


def _collect(
    cfg_or_dir: Union[AssetConfig, Path],
    exclude: Optional[List[str]] = None,
) -> List[Tuple[str, Path]]:
    """Returns sorted [(logical_name, absolute_path)] filtered by exclude patterns."""
    if isinstance(cfg_or_dir, AssetConfig):
        assets_dir = cfg_or_dir.assets_dir
        exclude_patterns = cfg_or_dir.exclude
    else:
        assets_dir = cfg_or_dir
        exclude_patterns = exclude or []

    if not assets_dir.is_dir():
        return []
    out: List[Tuple[str, Path]] = []
    for root, _, files in os.walk(assets_dir):
        for f in files:
            full = Path(root) / f
            rel = full.relative_to(assets_dir).as_posix()
            if any(fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(f, pat) for pat in exclude_patterns):
                continue
            # Do not embed explanatory README in the root of assets/
            if f == "README.md" and full.parent.resolve() == assets_dir.resolve():
                continue
            out.append((rel, full))
    return sorted(out, key=lambda t: t[0])


def _emit_header(module: str) -> str:
    """Generates C header declaring asset accessor functions."""
    return f"""/* Auto-generated by 'pengu assets' — DO NOT EDIT. */
#ifndef {module.upper()}_ASSETS_H
#define {module.upper()}_ASSETS_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

int _{module}_count(void);
char* _{module}_name(int index);
const void* _{module}_data(const char* name);
size_t _{module}_size(const char* name);

#ifdef __cplusplus
}}
#endif

#endif /* {module.upper()}_ASSETS_H */
"""


def _emit_embedded_c(module: str, assets: List[Tuple[str, Path]]) -> str:
    """Generates C source with static const hex byte arrays for embed=True mode."""
    lines = [
        "/* Auto-generated by 'pengu assets' — DO NOT EDIT. */",
        "/* Mode: embedded (assets compiled into .rodata). */",
        f'#include "{module}_assets.h"',
        "#include <stddef.h>",
        "#include <string.h>",
        "#include <stdbool.h>",
        "",
    ]
    entries = []
    for name, path in assets:
        data = path.read_bytes()
        ident = _c_ident(name)
        lines.append(f"/* {name} ({len(data)} bytes) */")
        lines.append(f"static const unsigned char {ident}[] = {{")
        if data:
            for i in range(0, len(data), 16):
                chunk = data[i : i + 16]
                row = ", ".join(f"0x{b:02X}" for b in chunk)
                lines.append(f"  {row},")
        lines.append("  0x00,")
        lines.append("};")
        lines.append("")
        entries.append((name, ident, len(data)))

    lines.append("typedef struct { const char* name; const void* data; size_t size; } _PenguAssetEntry;")
    lines.append("static const _PenguAssetEntry _pengu_assets[] = {")
    if not entries:
        lines.append("  { NULL, NULL, 0 },")
    else:
        for name, ident, size in entries:
            lines.append(f'  {{ "{_c_escape(name)}", {ident}, (size_t){size} }},')
    lines.append("};")
    lines.append("")

    count = len(assets)
    lines.append(f"""int _{module}_count(void) {{
    return {count};
}}

char* _{module}_name(int index) {{
    if (index < 0 || index >= {count}) return NULL;
    return (char*)_pengu_assets[index].name;
}}

const void* _{module}_data(const char* name) {{
    if (!name) return NULL;
    for (int i = 0; i < {count}; ++i) {{
        if (_pengu_assets[i].name && strcmp(_pengu_assets[i].name, name) == 0) {{
            return _pengu_assets[i].data;
        }}
    }}
    return NULL;
}}

size_t _{module}_size(const char* name) {{
    if (!name) return 0;
    for (int i = 0; i < {count}; ++i) {{
        if (_pengu_assets[i].name && strcmp(_pengu_assets[i].name, name) == 0) {{
            return _pengu_assets[i].size;
        }}
    }}
    return 0;
}}
""")
    return "\n".join(lines)


def _emit_disk_c(module: str, assets: List[Tuple[str, Path]], assets_dir_name: str = DEFAULT_ASSETS_DIR) -> str:
    """Generates C source that reads assets from disk with in-memory caching (embed=False mode)."""
    names_c = ", ".join(f'"{_c_escape(n)}"' for n, _ in assets) or "NULL"
    count = len(assets)
    escaped_dir_name = _c_escape(assets_dir_name)

    return f"""/* Auto-generated by 'pengu assets' — DO NOT EDIT. */
/* Mode: disk (assets read at runtime from the `{assets_dir_name}/` directory). */
#include "{module}_assets.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>

#define ARCA_ASSET_DIR_ENV "PENGU_ASSETS_DIR"
#define ARCA_DEFAULT_DIR "{escaped_dir_name}"

static const char* _arca_names[] = {{ {names_c} }};

typedef struct {{ char* name; unsigned char* data; size_t size; int attempted; }} _ArcaCacheEntry;
static _ArcaCacheEntry* _arca_cache = NULL;
static size_t _arca_cache_cap = 0;

static _ArcaCacheEntry* _arca_find(const char* name) {{
    for (size_t i = 0; i < _arca_cache_cap; ++i) {{
        if (_arca_cache[i].name && strcmp(_arca_cache[i].name, name) == 0) {{
            return &_arca_cache[i];
        }}
    }}
    return NULL;
}}

static _ArcaCacheEntry* _arca_insert(const char* name) {{
    _ArcaCacheEntry* new_cache = (_ArcaCacheEntry*)realloc(_arca_cache, (_arca_cache_cap + 1) * sizeof(_ArcaCacheEntry));
    if (!new_cache) return NULL;
    _arca_cache = new_cache;
    _ArcaCacheEntry* e = &_arca_cache[_arca_cache_cap++];
    e->name = (char*)malloc(strlen(name) + 1);
    if (e->name) {{
        strcpy(e->name, name);
    }}
    e->data = NULL;
    e->size = 0;
    e->attempted = 0;
    return e;
}}

static const char* _arca_dir(void) {{
    const char* env = getenv(ARCA_ASSET_DIR_ENV);
    return env ? env : ARCA_DEFAULT_DIR;
}}

static void _arca_load(const char* name) {{
    _ArcaCacheEntry* e = _arca_find(name);
    if (!e) e = _arca_insert(name);
    if (!e || e->attempted) return;
    e->attempted = 1;
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", _arca_dir(), name);
    FILE* f = fopen(path, "rb");
    if (!f) return;
    if (fseek(f, 0, SEEK_END) != 0) {{ fclose(f); return; }}
    long sz = ftell(f);
    if (fseek(f, 0, SEEK_SET) != 0 || sz < 0) {{ fclose(f); return; }}
    e->data = (unsigned char*)malloc((size_t)sz + 1);
    if (e->data) {{
        e->size = fread(e->data, 1, (size_t)sz, f);
        e->data[e->size] = 0;
    }}
    fclose(f);
}}

int _{module}_count(void) {{
    return {count};
}}

char* _{module}_name(int index) {{
    if (index < 0 || index >= {count}) return NULL;
    return (char*)_arca_names[index];
}}

const void* _{module}_data(const char* name) {{
    if (!name) return NULL;
    _arca_load(name);
    _ArcaCacheEntry* e = _arca_find(name);
    return e ? e->data : NULL;
}}

size_t _{module}_size(const char* name) {{
    if (!name) return 0;
    _arca_load(name);
    _ArcaCacheEntry* e = _arca_find(name);
    return e ? e->size : 0;
}}
"""


def _emit_interface(module: str, names: List[str], assets_dir_name: str = DEFAULT_ASSETS_DIR) -> str:
    """Generates src/<module>.pengu — identical in both embed and disk modes."""
    listing = "\n".join(f"##   - {n}" for n in names) if names else "##   (no assets)"
    const_lines = [f'const {_asset_const_name(n)} as string is "{n}"' for n in names]
    constants_block = ("\n" + "\n".join(const_lines) + "\n") if const_lines else ""

    return f'''## @generated — auto-generated by `pengu assets`. DO NOT EDIT.
## Regenerate with: pengu assets
##
## Embedded project assets (module: {module}).
## Source: {assets_dir_name}/
##
{listing}

include "{module}_assets.h"
import std.ffi
{constants_block}
declare _{module}_count into int
declare _{module}_name with index as int into ref to char
declare _{module}_data with name as ref to frozen char into ref to frozen void
declare _{module}_size with name as ref to frozen char into usize

## Returns the number of embedded assets.
weave count into int:
    return calling _{module}_count

## Returns the name of the asset at `index`, or "" if out of range.
weave name with index as int into string:
    let p as ref to char is calling _{module}_name with index
    if p == null:
        return ""
    return calling ffi.string_from_cstr with p

## Alias for `name`.
weave name_at with index as int into string:
    return calling name with index

## Returns the size in bytes of the asset, or 0 if not found.
weave size with name as string into usize:
    let c as ref to char is calling ffi.cstr_from_string with name
    return calling _{module}_size with (transmute c to ref to frozen char)

## Returns true if an asset with `name` exists.
weave has with name as string into bool:
    return (calling size with name) > 0

## Alias for `has`.
weave exists with name as string into bool:
    return calling has with name

## Returns a read-only pointer to the asset bytes, or null if not found.
weave ptr with name as string into ref to frozen void:
    let c as ref to char is calling ffi.cstr_from_string with name
    return calling _{module}_data with (transmute c to ref to frozen char)

## Returns a byte-slice view over the asset (empty if not found).
weave bytes with name as string into slice of byte:
    let p as ref to frozen void is calling ptr with name
    if (transmute p to usize) == 0:
        return calling ffi.slice_from_ptr of byte with (transmute 0 to ref to frozen byte), 0
    let sz as usize is calling size with name
    return calling ffi.slice_from_ptr of byte with (transmute p to ref to frozen byte), (sz to int)

## Returns the asset content as an owned string, or "" if not found.
weave string with name as string into string:
    let p as ref to frozen void is calling ptr with name
    if (transmute p to usize) == 0:
        return ""
    return calling ffi.string_from_cstr with (transmute p to ref to char)
'''


def generate(cfg: AssetConfig, force: bool = False) -> Optional[dict]:
    """Generates interface and implementation files.

    Returns dict with paths and digest, or None if assets_dir does not exist.
    """
    if not cfg.assets_dir.is_dir():
        return None

    assets = _collect(cfg)
    names = [n for n, _ in assets]

    src_interface = cfg.src_dir / f"{cfg.module}.pengu"
    build_c = cfg.build_dir / f"{cfg.module}_assets.c"
    build_header = cfg.build_dir / f"{cfg.module}_assets.h"
    hash_file = cfg.build_dir / f"{cfg.module}_assets.hash"

    cfg.src_dir.mkdir(parents=True, exist_ok=True)
    cfg.build_dir.mkdir(parents=True, exist_ok=True)

    assets_dir_name = cfg.assets_dir.name or DEFAULT_ASSETS_DIR
    interface_text = _emit_interface(cfg.module, names, assets_dir_name)
    header_text = _emit_header(cfg.module)
    c_text = _emit_embedded_c(cfg.module, assets) if cfg.embed else _emit_disk_c(cfg.module, assets, assets_dir_name)

    h = hashlib.sha256()
    h.update(f"embed={cfg.embed}\0module={cfg.module}\0".encode("utf-8"))
    for name, path in assets:
        h.update(name.encode("utf-8"))
        h.update(b"\0")
        try:
            h.update(hashlib.sha256(path.read_bytes()).hexdigest().encode("ascii"))
        except OSError:
            pass
        h.update(b"\0")

    digest = h.hexdigest()

    saved_digest = ""
    if hash_file.is_file():
        try:
            saved_digest = hash_file.read_text(encoding="utf-8").strip()
        except OSError:
            pass

    if force or saved_digest != digest or not src_interface.is_file() or not build_c.is_file() or not build_header.is_file():
        if not src_interface.is_file() or src_interface.read_text(encoding="utf-8") != interface_text:
            src_interface.write_text(interface_text, encoding="utf-8")
        if not build_header.is_file() or build_header.read_text(encoding="utf-8") != header_text:
            build_header.write_text(header_text, encoding="utf-8")
        if not build_c.is_file() or build_c.read_text(encoding="utf-8") != c_text:
            build_c.write_text(c_text, encoding="utf-8")
        try:
            hash_file.write_text(digest + "\n", encoding="utf-8")
        except OSError:
            pass

    return {
        "interface": str(src_interface),
        "interface_path": str(src_interface),
        "impl": str(build_c),
        "c_path": str(build_c),
        "header": str(build_header),
        "header_path": str(build_header),
        "hash_file": str(hash_file),
        "assets": names,
        "count": len(assets),
        "digest": digest,
    }
