#!/usr/bin/env python3
"""pengu_lock.py — `pengu.lock`: reproducible dependency pinning.

The lockfile records, for every dependency in the graph: the source URL, the
constraint from the manifest, the resolved version, the exact git commit and a
SHA-256 of the dependency's content tree.  `pengu build` keeps it up to date;
`--locked` verifies it, and `--frozen` additionally fails when it is missing
(so an offline/CI build can never silently resolve something new).

Format (TOML, roadmap 4.1)::

    version = 1
    targets = ["x86_64-unknown-linux-gnu"]

    [[package]]
    name = "leaf"
    source = "https://example.com/leaf.git"
    constraint = "^1.0.0"
    version = "1.0.0"
    commit = "a330b66..."
    sha256 = "..."
    required_by = ["parent"]
    children = []

The tree hash deliberately ignores VCS metadata, ``build/`` and caches so the
same checkout on another machine hashes identically.
"""

from __future__ import annotations

import hashlib
import os
import tomllib
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Optional, Tuple

LOCK_FILENAME = "pengu.lock"
LOCK_VERSION = 1

# Directories that are not part of a dependency's reproducible content.
_IGNORED_DIRS = {".git", ".hg", ".svn", "build", "__pycache__", ".venv", "node_modules"}


class LockError(RuntimeError):
    """Raised when the lockfile is missing or does not match the graph."""


@dataclass
class LockedPackage:
    name: str
    source: str = ""
    constraint: str = "*"
    version: str = ""
    commit: str = ""
    sha256: str = ""
    required_by: List[str] = field(default_factory=list)
    children: List[str] = field(default_factory=list)


@dataclass
class LockFile:
    version: int = LOCK_VERSION
    targets: List[str] = field(default_factory=list)
    packages: List[LockedPackage] = field(default_factory=list)

    def by_name(self) -> Dict[str, LockedPackage]:
        return {p.name: p for p in self.packages}


def compute_tree_hash(root: str) -> str:
    """Deterministic SHA-256 over a dependency's files (path + content)."""
    h = hashlib.sha256()
    if not os.path.isdir(root):
        return ""
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in _IGNORED_DIRS and not d.startswith("."))
        for fname in sorted(files):
            full = os.path.join(dirpath, fname)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            h.update(rel.encode("utf-8"))
            h.update(b"\0")
            try:
                with open(full, "rb") as f:
                    while True:
                        chunk = f.read(1 << 20)
                        if not chunk:
                            break
                        h.update(chunk)
            except OSError:
                h.update(b"<unreadable>")
            h.update(b"\0")
    return h.hexdigest()


def _git_commit(root: str) -> str:
    import subprocess
    if not os.path.isdir(os.path.join(root, ".git")):
        return ""
    try:
        res = subprocess.run(["git", "-C", root, "rev-parse", "HEAD"],
                             capture_output=True, text=True, timeout=60)
    except Exception:
        return ""
    return res.stdout.strip() if res.returncode == 0 else ""


def build_lock_from_graph(graph: Dict[str, object], target: str = "",
                          hash_trees: bool = True) -> LockFile:
    """Builds a :class:`LockFile` from ``resolve_transitive_dependencies`` output."""
    lock = LockFile(version=LOCK_VERSION, targets=[target] if target else [])
    for name in sorted(graph):
        node = graph[name]
        path = getattr(node, "path", "") or ""
        pkg = LockedPackage(
            name=name,
            source=getattr(node, "source", "") or "",
            constraint=getattr(node, "constraint", "") or "*",
            version=getattr(node, "resolved_version", "") or "",
            commit=getattr(node, "commit", "") or "",
            sha256=compute_tree_hash(path) if (hash_trees and path) else "",
            required_by=sorted(getattr(node, "required_by", []) or []),
            children=sorted(set(getattr(node, "children", []) or [])),
        )
        lock.packages.append(pkg)
    return lock


def dumps(lock: LockFile) -> str:
    """Serializes a lockfile to TOML text (deterministic key order)."""
    lines = [
        "# Auto-generated by 'pengu'. DO NOT EDIT.",
        f"version = {lock.version}",
    ]
    if lock.targets:
        rendered = ", ".join('"' + t + '"' for t in lock.targets)
        lines.append(f"targets = [{rendered}]")
    for pkg in lock.packages:
        lines.append("")
        lines.append("[[package]]")
        lines.append(f'name = "{pkg.name}"')
        lines.append(f'source = "{pkg.source}"')
        lines.append(f'constraint = "{pkg.constraint}"')
        lines.append(f'version = "{pkg.version}"')
        lines.append(f'commit = "{pkg.commit}"')
        lines.append(f'sha256 = "{pkg.sha256}"')
        lines.append("required_by = [" + ", ".join(f'"{r}"' for r in pkg.required_by) + "]")
        lines.append("children = [" + ", ".join(f'"{c}"' for c in pkg.children) + "]")
    return "\n".join(lines) + "\n"


def read_lock(base_dir: str) -> Optional[LockFile]:
    """Loads ``pengu.lock`` (None when absent or unreadable)."""
    path = os.path.join(base_dir, LOCK_FILENAME)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "rb") as f:
            data = tomllib.load(f)
    except Exception:
        return None
    lock = LockFile(
        version=int(data.get("version", LOCK_VERSION)),
        targets=[str(t) for t in data.get("targets", []) or []],
    )
    for entry in data.get("package", []) or []:
        if not isinstance(entry, dict):
            continue
        lock.packages.append(LockedPackage(
            name=str(entry.get("name", "")),
            source=str(entry.get("source", "")),
            constraint=str(entry.get("constraint", "*")),
            version=str(entry.get("version", "")),
            commit=str(entry.get("commit", "")),
            sha256=str(entry.get("sha256", "")),
            required_by=[str(r) for r in entry.get("required_by", []) or []],
            children=[str(c) for c in entry.get("children", []) or []],
        ))
    return lock


def write_lock(base_dir: str, lock: LockFile) -> str:
    """Writes ``pengu.lock`` and returns its path."""
    path = os.path.join(base_dir, LOCK_FILENAME)
    with open(path, "w", encoding="utf-8") as f:
        f.write(dumps(lock))
    return path


def diff_locks(expected: LockFile, actual: LockFile,
               target: str = "", check_hashes: bool = True) -> List[str]:
    """Human-readable differences between the locked and the current graph."""
    problems: List[str] = []
    if expected.version != actual.version:
        problems.append(f"lock version {expected.version} != expected {actual.version}")
    if target and expected.targets and target not in expected.targets:
        problems.append(
            f"pengu.lock was generated for {expected.targets}, not for target '{target}'"
        )
    exp = expected.by_name()
    act = actual.by_name()
    for name in sorted(set(exp) - set(act)):
        problems.append(f"'{name}' is in pengu.lock but missing from the project")
    for name in sorted(set(act) - set(exp)):
        problems.append(f"'{name}' is not recorded in pengu.lock")
    for name in sorted(set(exp) & set(act)):
        e, a = exp[name], act[name]
        if e.commit and a.commit and e.commit != a.commit:
            problems.append(f"'{name}' commit {a.commit} != locked {e.commit}")
        elif e.version != a.version:
            problems.append(f"'{name}' version {a.version or '?'} != locked {e.version or '?'}")
        if check_hashes and e.sha256 and a.sha256 and e.sha256 != a.sha256:
            problems.append(f"'{name}' content changed (sha256 mismatch)")
    return problems
