#!/usr/bin/env python3
"""regen_std_bindings.py - regenerate the tool-produced `std/*.d.pengu` bindings.

The bindings under ``std/`` are a mix of files produced by ``pengu bind`` and
hand-curated ones.  This script only rewrites the former:

* it recovers the generation options from the file itself (``include "X.h"``,
  ``insignia PREFIX``, unconditional ``link`` lines) and re-runs ``pengu bind``
  with the *current* generator,
* it keeps the hand-written preamble (the comment block above the
  ``generated by 'pengu bind'`` banner),
* and it refuses to write when the regenerated file would **lose** any
  declaration the committed file has (that means the file was hand-edited, e.g.
  raylib's colour constants), reporting it as hand-curated instead.

Usage::

    python regen_std_bindings.py --check     # report only (default)
    python regen_std_bindings.py --write     # apply
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from typing import Dict, List, Optional, Tuple

from pengu_bind import generate_bind_file

BANNER = "## PenguScript declaration binding generated by 'pengu bind'."
STD_DIR = "std"
SEARCH_DIRS = ["std_c", "build/include", "extern"]


def split_preamble(text: str) -> Tuple[List[str], str]:
    """Splits a binding into (hand-written preamble lines, generated text)."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == BANNER:
            return lines[:i], "\n".join(lines[i:])
    return [], text


DECL_KEYWORDS = {
    "declare", "const", "var", "let", "static", "alias", "rune", "omen", "echo",
    "seal", "concept", "insignia", "link", "include", "import", "bind", "where",
    "test", "inline", "many",
}


def declarations(text: str) -> Dict[str, str]:
    """Maps each declaration *identity* to its source line.

    The comparison must ignore spelling changes that are an improvement (a
    parameter gaining `frozen` is still the same declaration), so the identity
    is ``kind name`` for declared symbols and ``member name`` for indented
    struct fields / enum variants. Anything else (``when os == …``, ``link "x"``)
    keeps its literal text.
    """
    out: Dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_]\w*)\s+([A-Za-z_][\w\.]*)\s*[:=]?", stripped)
        if m and m.group(1) in DECL_KEYWORDS:
            out[f"{m.group(1)} {m.group(2)}"] = stripped
        elif line[:1] in (" ", "\t"):
            name = stripped.split()[0]
            out[f"member {name}"] = stripped
        else:
            out[stripped] = stripped
    return out


def recover_include(text: str) -> Optional[str]:
    m = re.search(r'^include\s+"([^"]+)"', text, re.MULTILINE)
    return m.group(1) if m else None


def recover_prefix(text: str) -> str:
    m = re.search(r"^insignia\s+(\S+)\s*$", text, re.MULTILINE)
    return m.group(1) if m else ""


def recover_links(text: str) -> List[str]:
    """Unconditional ``link "x"`` lines (platform-conditional ones are skipped)."""
    links: List[str] = []
    inside_when = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("when "):
            inside_when = True
            continue
        if inside_when:
            if stripped.startswith("else"):
                continue
            if stripped.startswith("link "):
                continue
            if stripped and not line.startswith((" ", "\t")):
                inside_when = False
        if not inside_when:
            m = re.match(r'^link\s+"([^"]+)"', stripped)
            if m:
                links.append(m.group(1))
    return links


def find_header(name: str, root: str) -> Optional[str]:
    for base in SEARCH_DIRS:
        direct = os.path.join(root, base, name)
        if os.path.isfile(direct):
            return direct
    for base in SEARCH_DIRS:
        for dirpath, _dirs, files in os.walk(os.path.join(root, base)):
            if name in files:
                return os.path.join(dirpath, name)
    return None


def regenerate(path: str, root: str, write: bool, show_diff: bool = False) -> Tuple[str, str]:
    """Regenerates one binding. Returns (status, detail)."""
    with open(path, "r", encoding="utf-8") as f:
        committed = f.read()
    preamble, _generated = split_preamble(committed)
    if not preamble and BANNER not in committed:
        return "skipped", "hand-written (no 'pengu bind' banner)"

    header_name = recover_include(committed)
    if not header_name:
        return "skipped", "no include line"
    header_path = find_header(header_name, root)
    if not header_path:
        return "skipped", f"header '{header_name}' not found"

    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, os.path.basename(path))
        generate_bind_file(
            header=header_path,
            output=out,
            prefix=recover_prefix(committed),
            links=recover_links(committed),
            include_paths=[os.path.join(root, "std_c"), os.path.join(root, "build/include"),
                           os.path.dirname(header_path)],
            auto_import=STD_DIR,
        )
        with open(out, "r", encoding="utf-8") as f:
            fresh = f.read()

    committed_decls = declarations(committed)
    fresh_decls = declarations(fresh)
    lost = [d for d in committed_decls if d not in fresh_decls]
    if lost:
        sample = "; ".join(lost[:3])
        return "skipped", f"hand-curated ({len(lost)} declarations would be lost: {sample})"

    result = ("\n".join(preamble) + "\n" if preamble else "") + fresh
    added = [d for d in fresh_decls if d not in committed_decls]
    removed = [d for d in committed_decls if d not in fresh_decls]
    if show_diff and result != committed:
        import difflib

        diff = difflib.unified_diff(committed.splitlines(), result.splitlines(),
                                    fromfile=f"a/{os.path.basename(path)}",
                                    tofile=f"b/{os.path.basename(path)}", lineterm="", n=1)
        print("\n".join(diff))
    if result == committed:
        return ("written" if write else "would-write"), "identical"
    detail = f"+{len(added)} new declarations, -{len(removed)} dropped"
    if write:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(result)
    return ("written" if write else "would-write"), detail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Apply the changes")
    parser.add_argument("--check", action="store_true", help="Report only (default)")
    parser.add_argument("--diff", action="store_true", help="Print the unified diff of each change")
    parser.add_argument("--only", default="", help="Regenerate only this file name (e.g. raygui.d.pengu)")
    args = parser.parse_args()
    root = os.path.dirname(os.path.abspath(__file__))
    std_dir = os.path.join(root, STD_DIR)

    counts = {"written": 0, "would-write": 0, "skipped": 0}
    for entry in sorted(os.listdir(std_dir)):
        if not entry.endswith(".d.pengu"):
            continue
        if args.only and entry != args.only:
            continue
        path = os.path.join(std_dir, entry)
        status, detail = regenerate(path, root, args.write, show_diff=args.diff)
        counts[status] = counts.get(status, 0) + 1
        print(f"[{status:11}] {entry:34} {detail}")
    print(f"\nwritten={counts['written']} would-write={counts['would-write']} "
          f"skipped={counts['skipped']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
