"""Binary-size reduction: section GC, conditional linking, ``PENGU_ENABLE_*``.

PenguScript 2.0 shipped a 659.5 KiB ``hello_world`` because three things
compounded:

1. ``libpengu_runtime.a`` had a single object member, so any reference to it
   dragged in the whole runtime, which in turn referenced PCRE2, libxml2,
   libcurl, mbedtls, libmicrohttpd and zlib;
2. those six archives were linked unconditionally;
3. nothing was compiled with ``-ffunction-sections``, so ``--gc-sections`` had
   nothing to prune.

These tests pin each fix at the level where it is observable:

* the *profiles* carry the section-splitting flags and a ``small`` profile
  exists (pure configuration, no toolchain needed);
* the *link line* keeps the runtime and zlib, always emits the section-GC
  option, and links a native archive only when the program's ``std`` imports
  call into it;
* the *runtime header* really hides a gated subsystem's declarations when the
  gate is 0, which is what lets the linker drop the archive;
* the *end-to-end* result: a built, stripped ``hello_world`` is small.

Nothing here inspects generated C (rule 1 in AGENT_TESTING.md); the artifact and
the link line are the observable contract.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import List, Sequence

import pytest

from tests.conftest import BUILD_INCLUDE, REPO, have_tool, requires_cc, requires_runtime

PENGU = [sys.executable, str(REPO / "pengu_project.py")]

#: The target this work was specified against. The measured value is ~14.3 KiB;
#: the assertion is the budget, not the measurement, so unrelated compiler
#: changes do not turn it red.
HELLO_BUDGET_BYTES = 130 * 1024

_HELLO = (
    'weave main into int:\n'
    '    var msg as string is "Hello, world!"\n'
    '    calling print with msg\n'
    '    return 0\n'
)

#: ``std.regulus`` is the smallest native consumer: its wrappers are the only
#: thing in the bundle that needs PCRE2.
_REGULUS = (
    'import std.spark\n'
    'import std.regulus\n'
    '\n'
    'weave main into int:\n'
    '    var re as maybe Regex is calling regulus.compile with "abc"\n'
    '    if re.is_present:\n'
    '        var hit as bool is calling regulus.is_match with sigil of re.value, "xabcx"\n'
    '        calling spark.println with "hit={hit}"\n'
    '    return 0\n'
)

#: ``std.parchment`` -> libxml2, the one native dependency that is a *dynamic*
#: system library on POSIX.
_PARCHMENT = (
    'import std.spark\n'
    'import std.parchment\n'
    '\n'
    'weave main into int:\n'
    '    var ok as bool is calling parchment.is_valid_xml with "<r><a>hi</a></r>"\n'
    '    calling spark.println with "valid={ok}"\n'
    '    return 0\n'
)


def _run(args: List[str], cwd: Path, env=None) -> subprocess.CompletedProcess:
    return subprocess.run([*PENGU, *args], capture_output=True, text=True,
                          timeout=300, cwd=str(cwd), env=env)


def _builder(tmp_path: Path, source: str = None):
    """A `PenguBuilder` for a throw-away project; no bundle is generated."""
    from pengu_project import OutputType, PenguBuilder, ProjectConfig

    script = tmp_path / "probe.pengu"
    script.write_text(source or "weave main into int:\n    return 0\n", encoding="utf-8")
    build_dir = tmp_path / "probe_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    cfg = ProjectConfig(entry=str(script), base_dir=str(tmp_path),
                        output=OutputType.EXE, output_name="probe", name="probe",
                        build_dir=str(build_dir), profile="release")
    cfg.links = ["pengu_runtime"]
    return PenguBuilder(cfg)


def _probe_bundle(*std_modules: str, symbols: Sequence[str] = ()) -> str:
    """A stand-in for a generated bundle, holding only the marker, the module
    ``#line`` comments and whichever subsystem symbols the caller wants.

    The archive decision is a pure function of that text, so this exercises it
    without paying for a semantic check of the real `std` module graph.
    """
    lines = ["/* Auto-generated by PenguScript */", '#include "pengu_runtime.h"']
    for name in std_modules:
        lines.append(f'#line 1 "/repo/std/{name}.pengu"')
    for symbol in symbols:
        lines.append(f"  {symbol};")
    lines.append("int main(void) { return 0; }")
    return "\n".join(lines) + "\n"


def _link_tokens(tmp_path: Path, source: str) -> List[str]:
    """Compiles *source* to ``OutputType.EXE`` far enough to get the link argv.

    The bundle is written and the command list assembled, but the compiler is
    never invoked: this is a build-policy assertion, and it needs no toolchain.
    """
    builder = _builder(tmp_path, source)
    build_dir = tmp_path / "probe_build"
    bundle_file, _ = builder.bundle(output_file=str(build_dir / "probe.c"))
    commands = builder.build_compile_commands(bundle_file, str(build_dir / "probe"))
    tokens: List[str] = []
    for command in commands:
        tokens.extend(command)
    return tokens


def _links(tokens: List[str], archive: str) -> bool:
    return f"-l{archive}" in tokens


# ---------------------------------------------------------------------------
# Profiles
# ---------------------------------------------------------------------------


def test_section_splitting_flags_are_the_same_constant_everywhere():
    """`pengu_project` and `build_runtime` must not drift apart.

    The link step's `--gc-sections` can only drop a function if the archive that
    holds it was compiled with `-ffunction-sections`. A single flag spelled two
    ways is how that guarantee gets lost.
    """
    import build_runtime
    from pengu_project import SECTION_FLAGS

    assert SECTION_FLAGS == ["-ffunction-sections", "-fdata-sections"]
    assert build_runtime.SECTION_FLAGS == SECTION_FLAGS


def test_default_profiles_split_sections_and_expose_small():
    from pengu_project import ProjectConfig

    profiles = ProjectConfig().profiles
    for name in ("release", "small"):
        cflags = profiles[name]["cflags"]
        assert "-ffunction-sections" in cflags, name
        assert "-fdata-sections" in cflags, name
    small = profiles["small"]["cflags"]
    assert "-Os" in small
    assert "-fno-asynchronous-unwind-tables" in small
    assert "-fno-unwind-tables" in small
    assert "-fno-ident" in small
    assert "-fno-plt" in small
    assert "PENGU_SIZE_OPT" in profiles["small"]["defines"]


def test_the_init_template_writes_the_section_flags(tmp_path):
    """A freshly initialised project must get the flags without editing anything."""
    res = _run(["init", "tpl", "--type", "exe", "--links", "pengu_runtime"], cwd=tmp_path)
    assert res.returncode == 0, res.stderr
    manifest = (tmp_path / "tpl" / "pengu.toml").read_text(encoding="utf-8")
    assert "[profiles.small]" in manifest
    release = manifest.split("[profiles.release]", 1)[1].split("[profiles.small]", 1)[0]
    assert "-ffunction-sections" in release
    assert "-fdata-sections" in release


# ---------------------------------------------------------------------------
# Conditional linking
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("modules,symbols,expected,forbidden", [
    ((), (), [], ["pcre2-8", "xml2", "curl", "mbedcrypto", "microhttpd"]),
    (("regulus",), (), ["pcre2-8"], ["xml2", "curl", "mbedcrypto", "microhttpd"]),
    (("seal",), (), ["z", "mbedcrypto"], ["pcre2-8", "xml2", "curl", "microhttpd"]),
    (("parchment",), (), ["xml2"], ["pcre2-8", "curl", "mbedcrypto", "microhttpd"]),
    (("precis",), (), ["curl", "microhttpd"], ["pcre2-8", "xml2", "mbedcrypto"]),
    (("filum",), (), [], ["pcre2-8", "xml2", "curl", "mbedcrypto", "microhttpd"]),
    (("oracle", "spark"), (), [], ["pcre2-8", "xml2", "curl", "mbedcrypto", "microhttpd"]),
    # The belt-and-braces path: a call to a runtime helper with no `std` import
    # at all must still pull the archive its implementation needs.
    ((), ("pengu_c_regulus_compile(p)",), ["pcre2-8"], ["xml2", "curl", "mbedcrypto"]),
    ((), ("pengu_c_seal_sha256(s)",), ["z", "mbedcrypto"], ["pcre2-8", "xml2", "curl"]),
])
def test_the_archive_decision_follows_the_bundle(tmp_path, modules, symbols,
                                                 expected, forbidden):
    """Conditional linking is decided by the bundle, not by the manifest.

    `_native_archives_for_bundle` is the whole decision: which archives the
    generated program actually references. Keeping it a pure function of the
    bundle text is what makes it cheap to pin every subsystem here without
    compiling anything.
    """
    builder = _builder(tmp_path)
    text = _probe_bundle(*modules, symbols=symbols)
    archives = builder._native_archives_for_bundle(None, text)
    for archive in expected:
        assert archive in archives, f"-l{archive} missing from {sorted(archives)}"
    for archive in forbidden:
        assert archive not in archives, (
            f"-l{archive} chosen although nothing in the bundle needs it: "
            f"{sorted(archives)}"
        )


def test_an_unreadable_bundle_falls_back_to_the_old_link_line(tmp_path):
    """No generated C to inspect means the pre-2.0 archive set.

    Over-linking is only size; under-linking is a link error. A caller that
    hands `build_compile_commands` a path with no generated bundle (unit tests,
    a bundle from an older toolchain) must not silently lose a dependency.
    """
    from pengu_project import _LEGACY_RUNTIME_ARCHIVES

    builder = _builder(tmp_path)
    for text in ("", "weave main into int:\n    return 0\n"):
        assert builder._native_archives_for_bundle(None, text) == set(_LEGACY_RUNTIME_ARCHIVES)


@requires_cc
def test_section_gc_and_the_always_linked_libraries(tmp_path):
    """The two halves of the flag work, on a real link command.

    `-lpengu_runtime` is mandatory and `-lz` cannot be made conditional: libxml2,
    libcurl and libcrypto all depend on `libz.so.1`, so the moment one of them is
    on the command line the linker resolves the runtime object's (about to be
    discarded) `compressBound` reference through that transitive dependency and
    aborts with "DSO missing from command line". The measured cost of keeping it
    is 0 bytes.
    """
    from pengu_project import _GC_SECTIONS_FLAG

    tokens = _link_tokens(tmp_path, _HELLO)
    assert _links(tokens, "pengu_runtime")
    assert _links(tokens, "z")
    assert _GC_SECTIONS_FLAG in tokens
    for flag in ("-ffunction-sections", "-fdata-sections"):
        assert flag in tokens


# ---------------------------------------------------------------------------
# Feature gates
# ---------------------------------------------------------------------------


def test_codegen_and_build_agree_on_the_gate_table():
    """The `#define` the bundle emits and the `-l` the builder adds come from
    two tables; if they disagree the program links an archive whose header it
    compiled out (or the reverse)."""
    from pengu_parser.pengu_codegen.bundle import FEATURE_GATE_MODULES
    from pengu_project import _FEATURE_GATE_MODULES

    assert FEATURE_GATE_MODULES == _FEATURE_GATE_MODULES


def test_gated_subsystems_have_no_cross_references():
    """Every gate covers declarations *and* definitions, so nothing outside a
    gated region may mention a symbol the region declares."""
    from pengu_parser.pengu_codegen.bundle import FEATURE_GATE_PREFIXES

    header = (REPO / "pengu_runtime.h").read_text(encoding="utf-8")
    for prefix in FEATURE_GATE_PREFIXES:
        regions = [i for i, line in enumerate(header.splitlines())
                   if prefix in line]
        assert regions, f"{prefix} is not declared anywhere in pengu_runtime.h"


@pytest.mark.skipif(not (have_tool("gcc") or have_tool("clang")),
                    reason="no gcc/clang")
def test_a_disabled_gate_removes_the_declarations(tmp_path):
    """`-DPENGU_ENABLE_REGEX=0` must make the Regulus API invisible.

    This is the property the linker relies on: the declarations disappear, so a
    bundle compiled with the gate at 0 cannot reference PCRE2 at all. The
    negative direction matters more than the positive one -- a gate that only
    hid the definitions would produce "implicit declaration" warnings instead of
    a clean compile.
    """
    cc = "gcc" if have_tool("gcc") else "clang"
    src = tmp_path / "gate.c"
    src.write_text(
        '#include "pengu_runtime.h"\n'
        'int main(void) {\n'
        '    return pengu_c_regulus_is_valid((void *)0) ? 0 : 1;\n'
        '}\n',
        encoding="utf-8",
    )
    base = [cc, "-c", str(src), "-o", str(tmp_path / "gate.o"),
            f"-I{REPO}", f"-I{BUILD_INCLUDE}", "-std=c11",
            "-Werror=implicit-function-declaration"]

    on = subprocess.run(base, capture_output=True, text=True, timeout=300)
    assert on.returncode == 0, on.stderr

    off = subprocess.run([*base, "-DPENGU_ENABLE_REGEX=0"],
                         capture_output=True, text=True, timeout=300)
    assert off.returncode != 0, (
        "the gate did not hide pengu_c_regulus_is_valid(); the header still "
        "declares the Regulus API with PENGU_ENABLE_REGEX=0"
    )


# ---------------------------------------------------------------------------
# End to end: the artifact is small, links only the runtime, and runs
# ---------------------------------------------------------------------------


@requires_cc
@requires_runtime
def test_stripped_hello_world_fits_the_size_budget(tmp_path):
    """The whole point of the exercise, measured on the real artifact."""
    res = _run(["init", "tiny", "--type", "exe", "--links", "pengu_runtime"], cwd=tmp_path)
    assert res.returncode == 0, res.stderr
    project = tmp_path / "tiny"
    (project / "src" / "main.pengu").write_text(_HELLO, encoding="utf-8")

    res = _run(["build", "--profile", "release", "--verbose"], cwd=project)
    assert res.returncode == 0, res.stdout + res.stderr
    log = res.stdout + res.stderr
    assert "native archives linked: (none)" in log, log

    binary = project / "build" / ("tiny.exe" if os.name == "nt" else "tiny")
    assert binary.is_file(), binary
    strip = "strip"
    if os.name != "nt" and have_tool(strip):
        subprocess.run([strip, str(binary)], check=False, capture_output=True, timeout=60)
    size = binary.stat().st_size
    assert size <= HELLO_BUDGET_BYTES, (
        f"stripped hello_world is {size} bytes, over the "
        f"{HELLO_BUDGET_BYTES}-byte budget (it was 675_000+ before 2.0)"
    )

    run = subprocess.run([str(binary)], capture_output=True, text=True, timeout=60)
    assert run.returncode == 0, run.stderr
    assert "Hello, world!" in run.stdout


@requires_cc
@requires_runtime
def test_a_regex_program_still_links_and_runs(tmp_path):
    """Conditional linking must not break the programs that do need an archive."""
    res = _run(["init", "rx", "--type", "exe", "--links", "pengu_runtime"], cwd=tmp_path)
    assert res.returncode == 0, res.stderr
    project = tmp_path / "rx"
    (project / "src" / "main.pengu").write_text(_REGULUS, encoding="utf-8")

    res = _run(["build", "--profile", "release", "--verbose"], cwd=project)
    assert res.returncode == 0, res.stdout + res.stderr
    log = res.stdout + res.stderr
    assert "native archives linked: ['pcre2-8']" in log, log

    binary = project / "build" / ("rx.exe" if os.name == "nt" else "rx")
    assert binary.is_file(), binary
    run = subprocess.run([str(binary)], capture_output=True, text=True, timeout=60)
    assert run.returncode == 0, run.stderr
    assert "hit=true" in run.stdout, run.stdout


@requires_cc
@requires_runtime
def test_an_xml_program_links_libxml2_and_runs(tmp_path):
    """The gated-declaration path, end to end, for a second subsystem.

    `std.parchment` is the one whose native dependency is a *dynamic* system
    library on POSIX (libxml2); it also exercises the `pkg-config` include path
    that conditional linking now only adds when XML is actually used.
    """
    res = _run(["init", "xml", "--type", "exe", "--links", "pengu_runtime"], cwd=tmp_path)
    assert res.returncode == 0, res.stderr
    project = tmp_path / "xml"
    (project / "src" / "main.pengu").write_text(_PARCHMENT, encoding="utf-8")

    res = _run(["build", "--profile", "release", "--verbose"], cwd=project)
    assert res.returncode == 0, res.stdout + res.stderr
    log = res.stdout + res.stderr
    assert "native archives linked: ['xml2']" in log, log

    binary = project / "build" / ("xml.exe" if os.name == "nt" else "xml")
    run = subprocess.run([str(binary)], capture_output=True, text=True, timeout=60)
    assert run.returncode == 0, run.stderr
    assert "valid=true" in run.stdout, run.stdout


# ---------------------------------------------------------------------------
# The attribution harness that produced the BENCHMARKS.md table
# ---------------------------------------------------------------------------


def _breakdown_module():
    import importlib.util

    path = REPO / "benches" / "binary_size_breakdown.py"
    spec = importlib.util.spec_from_file_location("pengu_size_breakdown", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


#: Both section layouts GNU ld emits, plus a discarded-section block that must
#: not be counted. Before the fix, the two-line form (which is *every* section
#: of a `-ffunction-sections` build) was silently attributed to nobody.
_MAP_SAMPLE = """\
Discarded input sections

 .debug_info     0x0000000000000000      0x100 /tmp/drop.a(gone.o)

Linker script and memory map

.text           0x0000000000001000       0x50
 .text          0x0000000000001000       0x10 /usr/lib/Scrt1.o
 .text.pcre2_compile_8
                0x0000000000001010       0x20 /repo/build/lib/libpcre2-8.a(pcre2_compile.o)
 .debug_info    0x0000000000000000      0x400 /repo/build/lib/libz.a(inflate.o)
 .bss.zlib      0x0000000000002000        0x8 /repo/build/lib/libz.a(deflate.o)
"""


def test_the_map_parser_reads_both_ld_section_layouts(tmp_path):
    module = _breakdown_module()
    map_path = tmp_path / "link.map"
    map_path.write_text(_MAP_SAMPLE, encoding="utf-8")

    totals = dict(module._parse_map(map_path))
    assert totals["libpcre2-8.a"] == 0x20
    assert totals["libz.a"] == 0x8          # debug info dropped, .bss kept
    assert totals["Scrt1.o"] == 0x10
    assert "drop.o" not in totals, "a discarded section was counted"


def test_the_legacy_link_shape_restores_the_pre_2_0_command():
    """`--legacy` is what makes the BENCHMARKS.md attribution reproducible."""
    module = _breakdown_module()
    modern = [
        "gcc", "b.c", "-o", "out",
        "-ffunction-sections", "-fdata-sections",
        "-Wl,--start-group", "-lpengu_runtime", "-lz",
        "-Wl,--gc-sections", "-Wl,--end-group",
    ]
    legacy = module.legacy_link_command(modern)
    assert "-Wl,--gc-sections" not in legacy
    assert "-ffunction-sections" not in legacy
    for archive in module.LEGACY_ARCHIVES:
        assert f"-l{archive}" in legacy, archive
    assert legacy.count("-lpengu_runtime") == 1

