typedef unsigned long pthread_t;
typedef void* pthread_attr_t;
typedef void* pthread_mutex_t;
typedef void* pthread_mutexattr_t;
typedef void* pthread_cond_t;
typedef void* pthread_condattr_t;
typedef void* pthread_rwlock_t;
typedef void* pthread_rwlockattr_t;
typedef unsigned int pthread_key_t;
typedef int pthread_once_t;
