typedef long long ssize_t;
typedef long long off_t;
typedef int pid_t;
typedef unsigned int uid_t;
typedef unsigned int gid_t;
typedef unsigned int mode_t;
typedef unsigned long long ino_t;
typedef unsigned int dev_t;
typedef unsigned int nlink_t;
typedef long long time_t;
typedef unsigned long long size_t;
typedef long long ptrdiff_t;
