#!/usr/bin/env python3
"""Generates a per-module API reference for the hand-written standard library.

Why this exists
---------------
Roadmap item 7.13 asks for an API reference built from the 1463 public names
(measured: **4014** public declarations across `std/`, or **1230** public
`weave`s). Writing that by hand is the kind of document that goes stale in a
week, so it is generated instead — from the same `render_module_doc` the
`pengu doc` command already uses, so there is exactly one renderer.

Scope
-----
The **27 hand-written modules** (`std/*.pengu`, excluding the generated
`*.d.pengu` bindings). The bindings' documentation text is the upstream C header
comment, so gating their coverage here would mean grading somebody else's
headers; `docs/DEPRECATIONS.md` and `LANGUAGE.md` §19 cover them instead.

What is verified
----------------
* every generated page is byte-identical to what the tool produces now
  (`--check`), so the reference cannot drift from the compiler;
* every public (non-`_`) declaration appears in its module's page;
* the share of public declarations that carry a summary does not regress
  (a ratchet, in the same style as the stdlib documentation ratchet).

Usage
-----
    python tools/gen_api_docs.py --write    # regenerate docs/api/
    python tools/gen_api_docs.py --check    # CI gate
    python tools/gen_api_docs.py --report   # coverage table only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

OUT_DIR = REPO / "docs" / "api"

#: Measured floor for the share of public declarations that carry a summary.
#: Measured at 94.1 % (1483/1576) across the 27 hand-written modules — above the
#: 90 % that roadmap item 7.13 asks for. Raise it when the number goes up; never
#: lower it. The remaining gap is `const` tables and a handful of `rune`s whose
#: meaning is in the name.
COVERAGE_FLOOR = 0.94


def _modules() -> list[Path]:
    """The hand-written stdlib modules, in a stable order."""
    return sorted(p for p in (REPO / "std").glob("*.pengu")
                  if not p.name.endswith(".d.pengu"))


def _builder_for(path: Path):
    """A ``PenguBuilder`` rooted at the module, exactly like `pengu check --entry`.

    Building the checker by hand does not work: a stdlib module needs the whole
    import graph (`std/archivum.pengu` calls `string.split`, which lives in
    `scrolls`), and only the builder passes `import_order` to the checker. This
    is the same construction `check_files` uses, so the reference documents what
    the CLI actually accepts.
    """
    from dataclasses import replace

    from pengu_project import PenguBuilder, ProjectConfig

    absolute = path.resolve()
    config = replace(
        ProjectConfig.load(None),
        base_dir=str(absolute.parent),
        entry=absolute.name,
        name=path.stem,
    )
    builder = PenguBuilder(config)
    builder.verbose = False
    return builder


def _render_one(path: Path) -> tuple[str, list[dict]]:
    """Returns ``(markdown, index_entries)`` for one module."""
    from pengu_doc import render_module_doc

    builder = _builder_for(path)
    ok, diagnostics = builder.check_sources_diagnostics()
    if not ok:
        first = diagnostics[0].get("message", "") if diagnostics else "unknown error"
        raise SystemExit(f"{path.relative_to(REPO)} does not check: {first}")

    doc = render_module_doc(str(path.resolve()), builder.checker,
                            [str(path.resolve())])

    public = [e for e in doc.index_entries if not e["name"].startswith("_")]
    documented = [e for e in public if (e.get("summary") or "").strip()]
    relative = path.relative_to(REPO).as_posix()
    lines = [
        f"# `std.{doc.module_name}`",
        "",
        f"> Source: [`{relative}`](../../{relative}) — "
        f"**{len(public)}** public declaration(s), "
        f"**{len(documented)}** of them documented.",
        "",
        "> Generated by [`tools/gen_api_docs.py`](../../tools/gen_api_docs.py) from the "
        "compiler's own symbol table. Do not edit by hand: "
        "`python tools/gen_api_docs.py --write`.",
        "",
        "---",
        "",
    ]
    body = "\n\n".join(rendered for _, rendered in doc.entries)
    lines.append(body if body else "_No public declarations._")
    lines.append("")
    return "\n".join(lines), public


def build() -> dict[str, str]:
    """``{relative output path: content}`` for every generated file."""
    pages: dict[str, str] = {}
    index: list[dict] = []
    coverage: list[tuple[str, int, int]] = []
    for path in _modules():
        content, public = _render_one(path)
        name = path.stem
        pages[f"{name}.md"] = content
        documented = sum(1 for e in public if (e.get("summary") or "").strip())
        coverage.append((name, documented, len(public)))
        for entry in public:
            index.append({
                "module": name,
                "kind": entry["kind"],
                "name": entry["name"],
                "signature": entry["signature"],
                "documented": bool((entry.get("summary") or "").strip()),
                "deprecated": bool(entry.get("deprecated")),
            })

    total_doc = sum(d for _, d, _ in coverage)
    total_all = sum(t for _, _, t in coverage)
    share = (total_doc / total_all) if total_all else 0.0

    lines = [
        "# Standard library API reference",
        "",
        "> Generated by [`../../tools/gen_api_docs.py`](../../tools/gen_api_docs.py) from the "
        "compiler's symbol table. Do not edit by hand.",
        "",
        f"**{total_all}** public declarations across **{len(coverage)}** hand-written "
        f"modules; **{total_doc}** of them carry a doc summary "
        f"({share * 100:.1f} %). Generated bindings (`std/*.d.pengu`) are out of "
        "scope here — their documentation text is the upstream C header comment.",
        "",
        "| Module | Public | Documented | Share |",
        "|---|---:|---:|---:|",
    ]
    for name, documented, public in coverage:
        pct = (documented / public * 100) if public else 0.0
        lines.append(f"| [`{name}`]({name}.md) | {public} | {documented} | {pct:.0f} % |")
    lines += [
        "",
        "The machine-readable form of this index is "
        "[`index.json`](index.json); `tests/test_api_docs.py` fails if it drifts "
        "from the compiler, or if a module documents fewer declarations than the "
        "recorded floor.",
        "",
    ]
    pages["README.md"] = "\n".join(lines)
    pages["index.json"] = json.dumps(
        {"coverage_floor": COVERAGE_FLOOR, "symbols": sorted(
            index, key=lambda e: (e["module"], e["kind"], e["name"]))},
        indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    return pages


def _on_disk() -> dict[str, str]:
    if not OUT_DIR.is_dir():
        return {}
    return {p.name: p.read_text(encoding="utf-8") for p in sorted(OUT_DIR.iterdir())
            if p.is_file()}


def cmd_write() -> int:
    pages = build()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in pages.items():
        (OUT_DIR / name).write_text(content, encoding="utf-8")
    try:
        where = OUT_DIR.relative_to(REPO)
    except ValueError:  # a test points OUT_DIR at a temporary directory
        where = OUT_DIR
    print(f"wrote {len(pages)} file(s) to {where}")
    return 0


def cmd_report() -> int:
    pages = build()
    for name, content in sorted(pages.items()):
        if name.endswith(".md") and name != "README.md":
            first = content.splitlines()[2]
            print(f"{name:24s} {first}")
    return 0


def coverage() -> tuple[int, int, float]:
    """``(documented, total, share)`` over the scoped public surface."""
    documented = total = 0
    for path in _modules():
        _, public = _render_one(path)
        total += len(public)
        documented += sum(1 for e in public if (e.get("summary") or "").strip())
    return documented, total, (documented / total if total else 0.0)


def cmd_check() -> int:
    expected = build()
    actual = _on_disk()
    problems: list[str] = []

    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if missing:
        problems.append(f"missing generated files: {missing}")
    if extra:
        problems.append(f"stale files that are not generated: {extra}")
    for name in sorted(set(expected) & set(actual)):
        if expected[name] != actual[name]:
            problems.append(f"{name}: content drifted from the compiler")

    # Derive coverage from the catalogue `build()` already produced, instead of
    # re-rendering all 27 modules a second time (~1 min).
    symbols = json.loads(expected["index.json"])["symbols"]
    total = len(symbols)
    documented = sum(1 for e in symbols if e["documented"])
    share = (documented / total) if total else 0.0
    if share < COVERAGE_FLOOR:
        problems.append(
            f"documented share {share * 100:.1f} % is below the floor "
            f"{COVERAGE_FLOOR * 100:.0f} % ({documented}/{total})"
        )

    if problems:
        print("api docs: OUT OF SYNC", file=sys.stderr)
        for line in problems:
            print("  " + line, file=sys.stderr)
        print("\nrun: python tools/gen_api_docs.py --write", file=sys.stderr)
        return 1
    print(f"api docs: {len(expected)} file(s) in sync, "
          f"{documented}/{total} public declarations documented ({share * 100:.1f} %)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate docs/api/")
    group.add_argument("--check", action="store_true", help="fail when docs/api/ has drifted")
    group.add_argument("--report", action="store_true", help="print the coverage table")
    args = parser.parse_args(argv)
    if args.write:
        return cmd_write()
    if args.report:
        return cmd_report()
    return cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
